url: http://brainpaste.blog
title: Brain Paste
description: Longer-form Ramblings From A Technologist
author: "Chad La Joie"
avatar: /images/logo.jpg

# Includes an icon in the footer for each username you enter
footer-links:
  github: lajoie
  linkedin: clajoie
  rss: true

#
# !! You don't need to change any of the configuration flags below !!
#
theme: jekyll-theme-tactile
permalink: /:title/
lsi: false
safe: true
incremental: false
timezone: American/New_York

gist:
  noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

plugins:
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

whitelist:
  - jekyll-feed


exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .ruby-version
