url: http://brainpaste.blog
title: Brain Paste
description: Longer-form Ramblings From A Technologist
author: "Chad La Joie"
avatar: /images/logo.jpg

# Includes an icon in the footer for each username you enter
footer-links:
  github: lajoie
  linkedin: clajoie
  rss: true

#
# !! You don't need to change any of the configuration flags below !!
#
theme: jekyll-theme-tactile
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
